import { CurrentClient, CallNote, Task, OpportunitySignal, Escalation } from './types';

export const seedClients: CurrentClient[] = [
  {
    id: 'c1',
    clientName: 'Acme Contracting',
    companyName: 'Acme Contracting LLC',
    contactName: 'John Doe',
    phone: '555-0101',
    email: 'john@acme.com',
    clientStatus: 'Active',
    greggPriority: 'High',
    riskLevel: 'Low',
    lastMeaningfulContact: '2023-10-20',
    nextAction: 'Review compliance docs',
    nextOwner: 'Gregg',
    dueDate: '2023-10-25',
    openTasks: 2,
    missingInformation: 'None',
    opportunitySignals: 0,
    escalations: 0,
    callNotes: 1
  },
  {
    id: 'c2',
    clientName: 'BuildCorp',
    companyName: 'BuildCorp Inc',
    contactName: 'Jane Smith',
    phone: '555-0102',
    email: 'jane@buildcorp.com',
    clientStatus: 'At Risk',
    greggPriority: 'Urgent',
    riskLevel: 'High',
    lastMeaningfulContact: '2023-10-18',
    nextAction: 'Address pricing exception',
    nextOwner: 'Gregg',
    dueDate: '2023-10-22',
    openTasks: 1,
    missingInformation: 'Pricing history',
    opportunitySignals: 1,
    escalations: 1,
    callNotes: 2
  },
  {
    id: 'c3',
    clientName: 'CityBuilders',
    companyName: 'CityBuilders Group',
    contactName: 'Bob Johnson',
    phone: '555-0103',
    email: 'bob@citybuilders.com',
    clientStatus: 'Renewal Pending',
    greggPriority: 'Medium',
    riskLevel: 'Medium',
    lastMeaningfulContact: '2023-10-15',
    nextAction: 'Send renewal agreement',
    nextOwner: 'Landon',
    dueDate: '2023-10-24',
    openTasks: 3,
    missingInformation: 'None',
    opportunitySignals: 0,
    escalations: 0,
    callNotes: 1
  },
  {
    id: 'c4',
    clientName: 'Delta Construction',
    companyName: 'Delta Construction Ltd',
    contactName: 'Alice Williams',
    phone: '555-0104',
    email: 'alice@deltaconstruction.com',
    clientStatus: 'Active',
    greggPriority: 'Low',
    riskLevel: 'Low',
    lastMeaningfulContact: '2023-10-10',
    nextAction: 'Check in on qualifier status',
    nextOwner: 'Landon',
    dueDate: '2023-10-30',
    openTasks: 0,
    missingInformation: 'Qualifier ID',
    opportunitySignals: 1,
    escalations: 0,
    callNotes: 1
  },
  {
    id: 'c5',
    clientName: 'Echo Builders',
    companyName: 'Echo Builders LLC',
    contactName: 'Charlie Brown',
    phone: '555-0105',
    email: 'charlie@echobuilders.com',
    clientStatus: 'Active',
    greggPriority: 'Medium',
    riskLevel: 'Low',
    lastMeaningfulContact: '2023-10-05',
    nextAction: 'Schedule monitoring call',
    nextOwner: 'Landon',
    dueDate: '2023-11-05',
    openTasks: 1,
    missingInformation: 'None',
    opportunitySignals: 1,
    escalations: 0,
    callNotes: 1
  },
  {
    id: 'c6',
    clientName: 'Foxtrot Developments',
    companyName: 'Foxtrot Developments Inc',
    contactName: 'David Lee',
    phone: '555-0106',
    email: 'david@foxtrot.com',
    clientStatus: 'Onboarding',
    greggPriority: 'High',
    riskLevel: 'Low',
    lastMeaningfulContact: '2023-10-21',
    nextAction: 'Complete onboarding',
    nextOwner: 'Gregg',
    dueDate: '2023-10-28',
    openTasks: 2,
    missingInformation: 'Company docs',
    opportunitySignals: 0,
    escalations: 0,
    callNotes: 2
  }
];

export const seedNotes: CallNote[] = [
  {
    id: 'n1',
    clientId: 'c1',
    callDate: '2023-10-20',
    caller: 'John Doe',
    callType: 'Inbound',
    rawRingCentralNote: 'John called to ask about the compliance docs. He said he will send them by tomorrow. Also mentioned he might need help with a new project next month.',
    cleanSummary: 'Discussed compliance documentation status and potential new project expansion.',
    clientConcern: 'None',
    commitmentsMade: 'John to send compliance docs by tomorrow.',
    missingInformation: 'Compliance docs',
    nextActions: 'Review compliance docs once received.',
    opportunitySignals: 'Expansion',
    escalationFlags: 'None',
    routingStatus: 'CRM-ready',
    crmReadyNote: 'Call with John Doe on 2023-10-20. Discussed compliance documentation status and potential new project expansion. Client concern/request: None. Missing information: Compliance docs. Next steps: Review compliance docs once received. Owner: Gregg. Due date: 2023-10-25. Opportunity signals: Expansion. Escalation: None.',
    clientFollowUpDraft: 'Hi John Doe, thank you for speaking with Gregg today. Based on the conversation, our next step is Review compliance docs once received. We are currently waiting on Compliance docs. We will follow up by 2023-10-25.',
    taskList: 'Task: Review compliance docs | Owner: Gregg | Due: 2023-10-25 | Priority: High',
    createdAt: '2023-10-20T10:00:00Z',
    updatedAt: '2023-10-20T10:30:00Z'
  },
  {
    id: 'n2',
    clientId: 'c2',
    callDate: '2023-10-18',
    caller: 'Jane Smith',
    callType: 'Escalation',
    rawRingCentralNote: 'Jane was very upset about the pricing exception we discussed last week. She says she will cancel if we don\'t honor the original quote.',
    cleanSummary: 'Client escalated regarding pricing exception and threatened cancellation.',
    clientConcern: 'Pricing exception not honored.',
    commitmentsMade: 'Gregg will review and provide a final decision by end of week.',
    missingInformation: 'Pricing history',
    nextActions: 'Review pricing exception and contact client.',
    opportunitySignals: 'Client-save',
    escalationFlags: 'Pricing exception',
    routingStatus: 'Gregg review',
    crmReadyNote: 'Call with Jane Smith on 2023-10-18. Discussed client escalated regarding pricing exception and threatened cancellation. Client concern/request: Pricing exception not honored. Missing information: Pricing history. Next steps: Review pricing exception and contact client. Owner: Gregg. Due date: 2023-10-22. Opportunity signals: Client-save. Escalation: Pricing exception.',
    clientFollowUpDraft: 'Hi Jane Smith, thank you for speaking with Gregg today. Based on the conversation, our next step is Review pricing exception and contact client. We are currently waiting on Pricing history. We will follow up by 2023-10-22.',
    taskList: 'Task: Address pricing exception | Owner: Gregg | Due: 2023-10-22 | Priority: Urgent',
    createdAt: '2023-10-18T14:00:00Z',
    updatedAt: '2023-10-18T14:45:00Z'
  },
  {
    id: 'n3',
    clientId: 'c3',
    callDate: '2023-10-15',
    caller: 'Bob Johnson',
    callType: 'Renewal',
    rawRingCentralNote: 'Bob wants to renew but asked if we can add monitoring to the package. Needs the renewal agreement sent over for signature.',
    cleanSummary: 'Client confirmed renewal intent and asked about adding monitoring services.',
    clientConcern: 'Wants monitoring added to renewal.',
    commitmentsMade: 'Landon to send renewal agreement.',
    missingInformation: 'None',
    nextActions: 'Send renewal agreement\nPrepare monitoring add-on quote',
    opportunitySignals: 'Expansion - monitoring add-on',
    escalationFlags: 'None',
    routingStatus: 'Summary drafted',
    crmReadyNote: 'Call with Bob Johnson on 2023-10-15. Discussed client confirmed renewal intent and asked about adding monitoring services. Client concern/request: Wants monitoring added to renewal. Missing information: None. Next steps: Send renewal agreement; Prepare monitoring add-on quote. Owner: Landon. Due date: 2023-10-24. Opportunity signals: Expansion - monitoring add-on. Escalation: None.',
    clientFollowUpDraft: 'Hi Bob Johnson, thank you for speaking with Gregg today. Based on the conversation, our next step is Send renewal agreement. We are currently waiting on nothing at this time. We will follow up by 2023-10-24.',
    taskList: 'Task: Send renewal agreement | Owner: Landon | Due: 2023-10-24 | Priority: Medium\nTask: Prepare monitoring add-on quote | Owner: Landon | Due: 2023-10-24 | Priority: Medium',
    createdAt: '2023-10-15T09:00:00Z',
    updatedAt: '2023-10-15T09:20:00Z'
  },
  {
    id: 'n4',
    clientId: 'c4',
    callDate: '2023-10-10',
    caller: 'Alice Williams',
    callType: 'Qualifier Discussion',
    rawRingCentralNote: 'Alice asked about qualifier requirements for a new state license. Could not confirm her current qualifier ID on file. Said she may want to add a second qualifier later.',
    cleanSummary: 'Discussed qualifier requirements for a new state license expansion.',
    clientConcern: 'Unsure of qualifier requirements for new state.',
    commitmentsMade: 'Landon to confirm qualifier ID and requirements.',
    missingInformation: 'Qualifier ID',
    nextActions: 'Confirm qualifier ID on file\nResearch new state qualifier requirements',
    opportunitySignals: 'Qualifier - potential second qualifier',
    escalationFlags: 'None',
    routingStatus: 'In review',
    crmReadyNote: 'Call with Alice Williams on 2023-10-10. Discussed qualifier requirements for a new state license expansion. Client concern/request: Unsure of qualifier requirements for new state. Missing information: Qualifier ID. Next steps: Confirm qualifier ID on file; Research new state qualifier requirements. Owner: Landon. Due date: 2023-10-30. Opportunity signals: Qualifier - potential second qualifier. Escalation: None.',
    clientFollowUpDraft: 'Hi Alice Williams, thank you for speaking with Gregg today. Based on the conversation, our next step is Confirm qualifier ID on file. We are currently waiting on Qualifier ID. We will follow up by 2023-10-30.',
    taskList: 'Task: Confirm qualifier ID on file | Owner: Landon | Due: 2023-10-30 | Priority: Medium\nTask: Research new state qualifier requirements | Owner: Landon | Due: 2023-10-30 | Priority: Medium',
    createdAt: '2023-10-10T11:00:00Z',
    updatedAt: '2023-10-10T11:25:00Z'
  },
  {
    id: 'n5',
    clientId: 'c5',
    callDate: '2023-10-05',
    caller: 'Charlie Brown',
    callType: 'Monitoring',
    rawRingCentralNote: 'Routine monitoring check-in. Everything looks fine. Charlie mentioned a colleague at another company might be interested in our services.',
    cleanSummary: 'Routine monitoring check-in with a potential referral lead.',
    clientConcern: 'None',
    commitmentsMade: 'Landon to schedule next monitoring call.',
    missingInformation: 'None',
    nextActions: 'Schedule next monitoring call',
    opportunitySignals: 'Placement - referral lead at another company',
    escalationFlags: 'None',
    routingStatus: 'CRM-ready',
    crmReadyNote: 'Call with Charlie Brown on 2023-10-05. Discussed routine monitoring check-in with a potential referral lead. Client concern/request: None. Missing information: None. Next steps: Schedule next monitoring call. Owner: Landon. Due date: 2023-11-05. Opportunity signals: Placement - referral lead at another company. Escalation: None.',
    clientFollowUpDraft: 'Hi Charlie Brown, thank you for speaking with Gregg today. Based on the conversation, our next step is Schedule next monitoring call. We are currently waiting on nothing at this time. We will follow up by 2023-11-05.',
    taskList: 'Task: Schedule next monitoring call | Owner: Landon | Due: 2023-11-05 | Priority: Low',
    createdAt: '2023-10-05T13:00:00Z',
    updatedAt: '2023-10-05T13:15:00Z'
  },
  {
    id: 'n6',
    clientId: 'c6',
    callDate: '2023-10-21',
    caller: 'David Lee',
    callType: 'Scheduled Check-in',
    rawRingCentralNote: 'Onboarding call. David still needs to send company formation docs and insurance certificate. Asked a question about legal liability that we should not answer directly.',
    cleanSummary: 'Onboarding check-in; outstanding documents and a legal-sensitive question raised.',
    clientConcern: 'Asked about legal liability exposure (decision boundary).',
    commitmentsMade: 'Gregg to follow up after collecting onboarding docs.',
    missingInformation: 'Company formation docs, insurance certificate',
    nextActions: 'Collect company formation docs\nRoute legal-liability question to leadership',
    opportunitySignals: 'None',
    escalationFlags: 'Legal-sensitive question raised - route to leadership review',
    routingStatus: 'Gregg review',
    crmReadyNote: 'Call with David Lee on 2023-10-21. Discussed onboarding check-in; outstanding documents and a legal-sensitive question raised. Client concern/request: Asked about legal liability exposure (decision boundary). Missing information: Company formation docs, insurance certificate. Next steps: Collect company formation docs; Route legal-liability question to leadership. Owner: Gregg. Due date: 2023-10-28. Opportunity signals: None. Escalation: Legal-sensitive question raised - route to leadership review.',
    clientFollowUpDraft: 'Hi David Lee, thank you for speaking with Gregg today. Based on the conversation, our next step is Collect company formation docs. We are currently waiting on Company formation docs, insurance certificate. We will follow up by 2023-10-28.',
    taskList: 'Task: Collect company formation docs | Owner: Gregg | Due: 2023-10-28 | Priority: High\nTask: Route legal-liability question to leadership | Owner: Gregg | Due: 2023-10-28 | Priority: High',
    createdAt: '2023-10-21T15:00:00Z',
    updatedAt: '2023-10-21T15:30:00Z'
  },
  {
    id: 'n7',
    clientId: 'c2',
    callDate: '2023-10-12',
    caller: 'Jane Smith',
    callType: 'Inbound',
    rawRingCentralNote: 'Jane called about a refund request for a duplicate charge. Wants money back this week. Did not have the invoice number handy.',
    cleanSummary: 'Client requested a refund for a reported duplicate charge.',
    clientConcern: 'Refund for duplicate charge.',
    commitmentsMade: 'Gregg to review billing and respond.',
    missingInformation: 'Invoice number',
    nextActions: 'Review billing records for duplicate charge',
    opportunitySignals: 'None',
    escalationFlags: 'Refund request - requires leadership approval',
    routingStatus: 'New',
    crmReadyNote: 'Call with Jane Smith on 2023-10-12. Discussed client requested a refund for a reported duplicate charge. Client concern/request: Refund for duplicate charge. Missing information: Invoice number. Next steps: Review billing records for duplicate charge. Owner: Gregg. Due date: 2023-10-16. Opportunity signals: None. Escalation: Refund request - requires leadership approval.',
    clientFollowUpDraft: 'Hi Jane Smith, thank you for speaking with Gregg today. Based on the conversation, our next step is Review billing records for duplicate charge. We are currently waiting on Invoice number. We will follow up by 2023-10-16.',
    taskList: 'Task: Review billing records for duplicate charge | Owner: Gregg | Due: 2023-10-16 | Priority: High',
    createdAt: '2023-10-12T10:00:00Z',
    updatedAt: '2023-10-12T10:20:00Z'
  },
  {
    id: 'n8',
    clientId: 'c6',
    callDate: '2023-10-08',
    caller: 'David Lee',
    callType: 'Placement Discussion',
    rawRingCentralNote: 'David wants to place a new qualifier for an upcoming bid. Needs approval on the placement and asked when it can be finalized.',
    cleanSummary: 'Client requested a qualifier placement for an upcoming bid.',
    clientConcern: 'Timeline for placement approval.',
    commitmentsMade: 'Gregg to review placement and confirm timeline.',
    missingInformation: 'Bid deadline',
    nextActions: 'Review placement request\nConfirm placement timeline with client',
    opportunitySignals: 'Placement - new qualifier placement',
    escalationFlags: 'Placement approval needed',
    routingStatus: 'New',
    crmReadyNote: 'Call with David Lee on 2023-10-08. Discussed client requested a qualifier placement for an upcoming bid. Client concern/request: Timeline for placement approval. Missing information: Bid deadline. Next steps: Review placement request; Confirm placement timeline with client. Owner: Gregg. Due date: 2023-10-14. Opportunity signals: Placement - new qualifier placement. Escalation: Placement approval needed.',
    clientFollowUpDraft: 'Hi David Lee, thank you for speaking with Gregg today. Based on the conversation, our next step is Review placement request. We are currently waiting on Bid deadline. We will follow up by 2023-10-14.',
    taskList: 'Task: Review placement request | Owner: Gregg | Due: 2023-10-14 | Priority: High\nTask: Confirm placement timeline with client | Owner: Gregg | Due: 2023-10-14 | Priority: High',
    createdAt: '2023-10-08T16:00:00Z',
    updatedAt: '2023-10-08T16:25:00Z'
  }
];

export const seedTasks: Task[] = [
  {
    id: 't1',
    clientId: 'c1',
    sourceCallNoteId: 'n1',
    title: 'Review compliance docs',
    owner: 'Gregg',
    dueDate: '2023-10-25',
    priority: 'High',
    status: 'Open',
    escalationFlag: false,
    notes: 'Review the docs John is sending.'
  },
  {
    id: 't2',
    clientId: 'c2',
    sourceCallNoteId: 'n2',
    title: 'Address pricing exception',
    owner: 'Gregg',
    dueDate: '2023-10-22',
    priority: 'Urgent',
    status: 'Open',
    escalationFlag: true,
    notes: 'Client threatened cancellation.'
  }
];

export const seedSignals: OpportunitySignal[] = [
  {
    id: 's1',
    clientId: 'c1',
    sourceCallNoteId: 'n1',
    type: 'Expansion',
    description: 'Potential new project next month.',
    status: 'Open',
    routedTo: 'Gregg',
    createdAt: '2023-10-20T10:30:00Z'
  },
  {
    id: 's2',
    clientId: 'c2',
    sourceCallNoteId: 'n2',
    type: 'Client-save',
    description: 'Client escalated pricing exception.',
    status: 'Open',
    routedTo: 'Gregg',
    createdAt: '2023-10-18T14:45:00Z'
  }
];

export const seedEscalations: Escalation[] = [
  {
    id: 'e1',
    clientId: 'c2',
    sourceCallNoteId: 'n2',
    reason: 'Pricing exception',
    riskLevel: 'High',
    routedTo: 'Gregg',
    decisionNeeded: 'Approve or deny pricing exception.',
    deadline: '2023-10-22',
    status: 'Open'
  }
];