import { Router, type IRouter } from "express";
import healthRouter from "./health";
import meRouter from "./me";
import clientsRouter from "./clients";
import auditLinksRouter from "./auditLinks";
import callNotesRouter from "./callNotes";
import tasksRouter from "./tasks";
import signalsRouter from "./signals";
import escalationsRouter from "./escalations";
import activityRouter from "./activity";
import viewStateRouter from "./viewState";
import adminRouter from "./admin";
import relationshipsRouter from "./relationships";
import expansionRouter from "./expansion";
import scheduledEventsRouter from "./scheduledEvents";
import contactLogRouter from "./contactLog";
import crmRouter from "./crm";
import reportsRouter from "./reports";
import communicationsRouter from "./communications";
import travelRouter from "./travel";
import expensesRouter from "./expenses";
import feedbackRouter from "./feedback";
import trainingRouter from "./training";
import bonusRouter from "./bonus";
import profitShareRouter from "./profitShare";
import qualifiersRouter from "./qualifiers";
import placementsRouter from "./placements";
import successPlanRouter from "./successPlan";
import { requireAuth } from "../middlewares/auth";

const router: IRouter = Router();

router.use(healthRouter);

router.use(requireAuth);

router.use(meRouter);
router.use(clientsRouter);
router.use(auditLinksRouter);
router.use(callNotesRouter);
router.use(tasksRouter);
router.use(signalsRouter);
router.use(escalationsRouter);
router.use(activityRouter);
router.use(viewStateRouter);
router.use(adminRouter);
router.use(relationshipsRouter);
router.use(expansionRouter);
router.use(scheduledEventsRouter);
router.use(contactLogRouter);
router.use(crmRouter);
router.use(reportsRouter);
router.use(communicationsRouter);
router.use(travelRouter);
router.use(expensesRouter);
router.use(feedbackRouter);
router.use(trainingRouter);
router.use(bonusRouter);
router.use(profitShareRouter);
router.use(qualifiersRouter);
router.use(placementsRouter);
router.use(successPlanRouter);

export default router;
